In [5]:
import pandas as pd
import numpy as np

In [4]:
index = pd.date_range("2018-1-1", "2018-12-1", freq="D")

In [7]:
len(index)

335

In [11]:
df = pd.DataFrame(np.random.randn(len(index)), index=index)

In [12]:
df

                   0
2018-01-01 -1.098453
2018-01-02  0.575747
2018-01-03 -0.614734
2018-01-04  1.211989
2018-01-05  0.657960
2018-01-06  0.810979
2018-01-07 -1.471030
2018-01-08  0.081714
2018-01-09  0.273029
2018-01-10 -1.049299
2018-01-11 -0.765382
2018-01-12 -1.472283
2018-01-13  0.307229
2018-01-14 -1.653776
2018-01-15 -0.099723
2018-01-16  0.145214
2018-01-17 -0.033725
2018-01-18  0.514284
2018-01-19  0.715389
2018-01-20  1.277362
2018-01-21  0.660934
2018-01-22 -0.355341
2018-01-23  0.088582
2018-01-24  0.701588
2018-01-25 -1.087933
2018-01-26 -0.877279
2018-01-27  0.326665
2018-01-28 -0.347926
2018-01-29  1.673731
2018-01-30  0.796353
...              ...
2018-11-02 -1.608467
2018-11-03  1.119804
2018-11-04  0.599280
2018-11-05 -0.969710
2018-11-06 -0.153879
2018-11-07  0.317790
2018-11-08  0.812963
2018-11-09  0.127139
2018-11-10  0.348411
2018-11-11  0.580891
2018-11-12 -1.300217
2018-11-13  1.256923
2018-11-14  0.919980
2018-11-15  1.344688
2018-11-16 -0.246006
2018-11-17  0.929704
2018-11-18  1.648953
2018-11-19  0.931313
2018-11-20 -2.653879
2018-11-21  0.528402
2018-11-22 -0.835814
2018-11-23  1.164548
2018-11-24 -0.800248
2018-11-25  0.493702
2018-11-26  1.403868
2018-11-27 -0.958641
2018-11-28  0.900869
2018-11-29  0.932316
2018-11-30  0.167076
2018-12-01 -1.112467

[335 rows x 1 columns]

In [13]:
df.reset_index(inplace=True)

In [14]:
df

         index         0
0   2018-01-01 -1.098453
1   2018-01-02  0.575747
2   2018-01-03 -0.614734
3   2018-01-04  1.211989
4   2018-01-05  0.657960
5   2018-01-06  0.810979
6   2018-01-07 -1.471030
7   2018-01-08  0.081714
8   2018-01-09  0.273029
9   2018-01-10 -1.049299
10  2018-01-11 -0.765382
11  2018-01-12 -1.472283
12  2018-01-13  0.307229
13  2018-01-14 -1.653776
14  2018-01-15 -0.099723
15  2018-01-16  0.145214
16  2018-01-17 -0.033725
17  2018-01-18  0.514284
18  2018-01-19  0.715389
19  2018-01-20  1.277362
20  2018-01-21  0.660934
21  2018-01-22 -0.355341
22  2018-01-23  0.088582
23  2018-01-24  0.701588
24  2018-01-25 -1.087933
25  2018-01-26 -0.877279
26  2018-01-27  0.326665
27  2018-01-28 -0.347926
28  2018-01-29  1.673731
29  2018-01-30  0.796353
..         ...       ...
305 2018-11-02 -1.608467
306 2018-11-03  1.119804
307 2018-11-04  0.599280
308 2018-11-05 -0.969710
309 2018-11-06 -0.153879
310 2018-11-07  0.317790
311 2018-11-08  0.812963
312 2018-11-09  0.127139
313 2018-11-10  0.348411
314 2018-11-11  0.580891
315 2018-11-12 -1.300217
316 2018-11-13  1.256923
317 2018-11-14  0.919980
318 2018-11-15  1.344688
319 2018-11-16 -0.246006
320 2018-11-17  0.929704
321 2018-11-18  1.648953
322 2018-11-19  0.931313
323 2018-11-20 -2.653879
324 2018-11-21  0.528402
325 2018-11-22 -0.835814
326 2018-11-23  1.164548
327 2018-11-24 -0.800248
328 2018-11-25  0.493702
329 2018-11-26  1.403868
330 2018-11-27 -0.958641
331 2018-11-28  0.900869
332 2018-11-29  0.932316
333 2018-11-30  0.167076
334 2018-12-01 -1.112467

[335 rows x 2 columns]

In [22]:
%timeit -n 1000 pd.to_datetime(df['index'], unit='h').dt.strftime("%H:%M")

2.07 ms Â± 28.2 Âµs per loop (mean Â± std. dev. of 7 runs, 1000 loops each)

In [21]:
%timeit -n 1000 df['index'].astype(np.str).str.pad(width=2, side='left', fillchar='0') + ':00'

2.09 ms Â± 38.5 Âµs per loop (mean Â± std. dev. of 7 runs, 1000 loops each)